[project]
name = "trolskgen"
version = "0.0.23"
description = "Cute Python codegen"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = ["codegen"]
authors = [
  {name = "Oliver Russell", email = "ojhrussell@gmail.com"},
]
maintainers = [
  {name = "Oliver Russell", email = "ojhrussell@gmail.com"},
]
classifiers = [
  "Programming Language :: Python",
]

dependencies = [
  "typing-extensions>=4.10.0",
]

[project.optional-dependencies]
dev = [
  "pytest==8.*",
  "ruff==0.11.*",
  "mypy==1.*",
  "rich==14.*",
  "pydantic==2.*",
]

[project.urls]
homepage = "https://github.com/leontrolski/trolskgen"

[tool.ruff]
line-length = 120

[tool.mypy]
strict = true
